### ISSUE TITLE
Plots of Cast Study Maps

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/demandmap#23]
...now that Bastian sent the shapefiles for his routes, get-to-plotting, please 🏃‍♂️

**Comment by dodedic** [comment]
**INITAL RESULTS**
@michaelweinold @arebe337 

So I've had a play around plotting the data that Bastian gave us. Still _very much_ WIP, will put in a considerable amount of time tomorrow to add everything that needs to be added. I will try to add terrain and other information tomorrow. This now serves as a little taste of what's to come.
But from an inital assessment both the route for Melbourne-Sydney and the one for LA-San Francisco seem to _**relatively closely**_ match what has been planned by lawmakers as you can see below. 😃 

**Melbourne-Sydney**
This one looks very good! It actually takes the perfect route through the valley in the "Southern Highlands"

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/e4105339-ada8-46d6-ac07-06138c4c857f" width="300">
<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/d4c6bf2d-db9c-4cf7-927c-68ad8f200f7e" width="300">

**LA-San Francisco**
This one deviates around Madera and continues up to Stockton on the actual route. This actually still is "good" since it's still taking a real route. In real-life they might have taking the route down to Gilroy for other reasons. Still the tool seems a success I would say.

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/cf43552e-55e3-43f2-94bb-9dbae2f0ead0" width="300">
<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/f757c789-92a0-4b23-8c9e-e280ad39f379" width="300">

**Lagos-Abuja**
And finally the new (yet to be released) official HSR project from Lagos to Abuja!

<img src="https://github.com/sustainableaviation/demandmap/assets/118805682/cc771962-ccad-4e0d-9894-cce835c4aa5b" width="300">

**Comment by michaelweinold** [comment]
Nice, nice, nice! I will think of a way to extract the proposed routes to GPS coordinates, such that we can overlay it on the calculated routes. Great work! ✨

**Comment by dodedic** [comment]
@michaelweinold @arebe337 
This would be my proposal for the maps that could go on the poster. I found a nice set of map styles from [mapbox](https://www.mapbox.com/) that also show terrain:

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/13d4ec2b-3afe-4bbd-b4f8-9af1f88fe034)

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/2da7ba8d-eeab-426c-ac03-3bacabec7d7a)

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/7bda3e42-8dd4-4ef5-abb8-4c1a67fe5bd7)

**Comment by michaelweinold** [comment]
Looks great - where is the associated code?

**Comment by dodedic** [comment]
Should now be in the [PR](https://github.com/sustainableaviation/demandmap/pull/26), which I have no released from draft.

**Comment by michaelweinold** [comment]
@dodedic, please add the extracted routes from the proposed routes in https://github.com/sustainableaviation/demandmap/issues/34 and open a PR.

**Comment by dodedic** [comment]
So this is how it's looking currently. 
green = real, purple = model

**California**
![image](https://github.com/sustainableaviation/demandmap/assets/118805682/c02d83cf-c3d4-426b-95d0-2e32ed45ca78)

**Australia**
![image](https://github.com/sustainableaviation/demandmap/assets/118805682/5daf60f5-bf27-4f0a-8bf0-62e62807a97a)

**Comment by michaelweinold** [comment]
Nota bene: Mapbox operates under a non-free license. I would suggest you look for alternative map tile providers for the interactive maps. For static maps, we can simply use the Natural Earth terrain tiles:

<img src="https://github.com/sustainableaviation/demandmap/assets/23102087/02cfd7af-9d10-4bea-ad09-a84c9d85f03e" width="300">


I will add them to the repo later today.
